// Ambient declaration for the build-time routes manifest generated by the
// rayactRouterPlugin Vite plugin (see src/vite/plugin.ts).
declare module 'virtual:rayact-routes' {
  export const ctx: Record<string, Record<string, unknown>>;
  export const appRoot: string;
}
