// Generated by raysvg tools/convert-rig; regenerate with tools/embed-asset.mjs.
// The pet rig embedded as text so the smoke test needs no on-device asset plumbing.
#ifndef RAYSVG_SMOKE_ASSET_H
#define RAYSVG_SMOKE_ASSET_H

static const char *const kRaysvgSmokeRig = R"RIGSVG(<!-- Generated by raysvg tools/convert-rig from the waddlers pet rig. Do not edit. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
  <defs>
            <clipPath id="belly-round-clip" clipPathUnits="userSpaceOnUse">
              <rect x="33" y="80" width="134" height="85" rx="42.5"/>
            </clipPath>
            <clipPath id="belly-square-clip" clipPathUnits="userSpaceOnUse">
              <rect x="35" y="80" width="130" height="85" rx="20"/>
            </clipPath>
          <linearGradient id="hover-beam-grad" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stop-color="#5eead4" stop-opacity="0.45"/>
            <stop offset="100%" stop-color="#22d3ee" stop-opacity="0"/>
          </linearGradient>
        <clipPath id="head-clip-mask">
          <circle cx="100" cy="85" r="75"/>
        </clipPath>
        <clipPath id="chicken-mouth-clip" clipPathUnits="userSpaceOnUse">
          <circle cx="100" cy="96" r="11"/>
        </clipPath>
  </defs>
  <g id="hover-floor-shadow" class="hover-floor-shadow">
    <ellipse id="hover-shadow-ellipse" cx="100" cy="198" rx="52" ry="10" fill="rgba(0,0,0,0.18)"/>
  </g>
  <g id="anim-wrapper" style="z-index: 2; transform-origin: 50% 92.5%">
    <g id="layer-tail" class="layer" style="z-index: 0">
      <g id="anim-tail" style="transform-origin: 100px 130px">
        <g class="part tail-bunny" style="display: none">
          <circle cx="121" cy="127" r="12" fill="#ffffff"/>
          <circle cx="110" cy="123" r="8" fill="#ffffff"/>
          <circle cx="112" cy="134" r="7" fill="#ffffff"/>
          <circle cx="128" cy="120" r="7.5" fill="#ffffff"/>
          <circle cx="130" cy="132" r="7" fill="#ffffff"/>
        </g>
        <g class="part tail-bear" style="display: none">
          <circle cx="117" cy="128" r="10" class="skin" style="fill: #ffe76a"/>
          <circle cx="112" cy="122" r="5" class="skin" style="fill: #ffe76a"/>
        </g>
        <g class="part tail-tanuki" style="display: none">
          <path d="M 115 130 C 130 115, 148 118, 148 133 C 148 146, 136 153, 125 150 C 116 148, 110 140, 115 130 Z" class="skin" style="fill: #ffe76a"/>
          <path d="M 125 124 C 137 124, 145 130, 145 136 C 139 135, 128 132, 119 128 Z" fill="rgba(26, 26, 26, 0.18)"/>
        </g>
        <g class="part tail-axolotl" style="display: none">
          <path d="M 115 130 Q 140 122, 146 134 Q 143 146, 132 151 Q 119 155, 110 147 Q 106 137, 115 130 Z" class="skin" style="fill: #ffe76a"/>
          <path d="M 121 135 Q 137 131, 143 136 Q 136 144, 122 147" class="toon-line" opacity="0.35" style="fill: none; stroke: #1a1a1a; stroke-width: 3.4px; stroke-linecap: round; stroke-linejoin: round"/>
        </g>
        <g class="part tail-goat" style="display: none">
          <g transform="translate(121 144) rotate(38) scale(0.4) translate(-169 -47)">
            <path d="M 108 46 Q 128 6 162 12 Q 144 34 126 48" class="skin" style="fill: #ffe76a"/>
          </g>
        </g>
      </g>
    </g>
    <g id="behind-group" style="z-index: 0">
    </g>
    <g id="blob-outline" class="blob-outline" style="z-index: 1">
      <g id="layer-leg-quad-back-left" class="layer" style="z-index: 1">
        <g class="part leg-quad-back" style="display: none">
          <g id="knee-l-b-wrap" style="transform-origin: 67.5px 160px">
            <rect x="60" y="155" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
            <g id="knee-l-b" style="transform-origin: 67.5px 165px">
              <circle cx="67.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
              <path d="M 60 162 L 60 168 C 60 178, 75 178, 75 168 L 75 162 Z" class="skin" style="fill: #ffe76a"/>
            </g>
          </g>
        </g>
      </g>
      <g id="layer-leg-quad-back-right" class="layer" style="z-index: 1">
        <g class="part leg-quad-back" style="display: none">
          <g id="knee-r-b-wrap" style="transform-origin: 132.5px 160px">
            <rect x="125" y="155" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
            <g id="knee-r-b" style="transform-origin: 132.5px 165px">
              <circle cx="132.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
              <path d="M 140 162 L 140 168 C 140 178, 125 178, 125 168 L 125 162 Z" class="skin" style="fill: #ffe76a"/>
            </g>
          </g>
        </g>
      </g>
      <g id="layer-leg-biped-back-left" class="layer" style="z-index: 1">
        <g id="anim-leg-biped-back-left" style="transform-origin: 65px 160px">
          <g class="part leg-biped-back" >
            <rect x="60" y="155" width="15" height="17.5" rx="7.5" class="skin" style="fill: #ffe76a"/>
            <g id="anim-knee-biped-back-left" style="transform-origin: 67.5px 165px">
              <circle cx="67.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
              <path d="M 60 162 L 60 168 C 60 178, 75 178, 75 168 L 75 162 Z" class="skin" style="fill: #ffe76a"/>
            </g>
          </g>
        </g>
      </g>
      <g id="layer-leg-biped-back-right" class="layer" style="z-index: 1">
        <g id="anim-leg-biped-back-right" style="transform-origin: 135px 160px">
          <g class="part leg-biped-back" >
            <rect x="125" y="155" width="15" height="17.5" rx="7.5" class="skin" style="fill: #ffe76a"/>
            <g id="anim-knee-biped-back-right" style="transform-origin: 132.5px 165px">
              <circle cx="132.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
              <path d="M 140 162 L 140 168 C 140 178, 125 178, 125 168 L 125 162 Z" class="skin" style="fill: #ffe76a"/>
            </g>
          </g>
        </g>
      </g>
      <g id="layer-leg-octo-back" class="layer" style="z-index: 1">
        <g id="anim-leg-octo-back-left" style="transform-origin: 65px 155px">
          <g class="part leg-octo" style="display: none">
            <g transform="translate(55, 156) rotate(-40)">
              <g id="ten-l-2-wrap" style="transform-origin: 0px 0px">
                <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                <g id="ten-l-2-knee" style="transform-origin: 0px 5px">
                  <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                  <path d="M -7.5 2 L -7.5 8 C -7.5 18, 7.5 18, 7.5 8 L 7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                </g>
              </g>
            </g>
          </g>
        </g>
        <g id="anim-leg-octo-back-right" style="transform-origin: 135px 155px">
          <g class="part leg-octo" style="display: none">
            <g transform="translate(145, 156) rotate(40)">
              <g id="ten-r-2-wrap" style="transform-origin: 0px 0px">
                <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                <g id="ten-r-2-knee" style="transform-origin: 0px 5px">
                  <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                  <path d="M 7.5 2 L 7.5 8 C 7.5 18, -7.5 18, -7.5 8 L -7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
      <g id="blob-group" style="z-index: 2">
        <g id="layer-leg-octo-back-blob" class="layer" style="z-index: 1">
          <g id="anim-leg-octo-back-left-blob" style="transform-origin: 65px 155px">
            <g class="part leg-octo-back-blob" style="display: none">
              <g transform="translate(55, 156) rotate(-40)">
                <g id="ten-l-2-blob-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-l-2-blob-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M -7.5 2 L -7.5 8 C -7.5 18, 7.5 18, 7.5 8 L 7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
            </g>
          </g>
          <g id="anim-leg-octo-back-right-blob" style="transform-origin: 135px 155px">
            <g class="part leg-octo-back-blob" style="display: none">
              <g transform="translate(145, 156) rotate(40)">
                <g id="ten-r-2-blob-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-r-2-blob-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M 7.5 2 L 7.5 8 C 7.5 18, -7.5 18, -7.5 8 L -7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-leg-left" class="layer" style="z-index: 5">
          <g id="anim-leg-left" style="transform-origin: 65px 160px">
            <g class="part leg-biped" >
              <rect x="60" y="155" width="15" height="17.5" rx="7.5" class="skin" style="fill: #ffe76a"/>
              <g id="anim-knee-left" style="transform-origin: 67.5px 165px">
                <circle cx="67.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
                <path d="M 60 162 L 60 168 C 60 178, 75 178, 75 168 L 75 162 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
            <g class="part leg-octo" style="display: none">
              <g transform="translate(85, 162) rotate(0)">
                <g id="ten-l-0-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-l-0-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M -7.5 2 L -7.5 8 C -7.5 18, 7.5 18, 7.5 8 L 7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
              <g transform="translate(65, 162) rotate(-20)">
                <g id="ten-l-1-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-l-1-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M -7.5 2 L -7.5 8 C -7.5 18, 7.5 18, 7.5 8 L 7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
              <g transform="translate(48, 158) rotate(-42)">
                <g id="ten-l-3-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-l-3-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M -7.5 2 L -7.5 8 C -7.5 18, 7.5 18, 7.5 8 L 7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
            </g>
            <g class="part leg-block" style="display: none">
              <rect x="55" y="150" width="20" height="35" rx="6" ry="6" class="arm-outline" style="display: none"/>
              <rect x="55" y="150" width="20" height="35" rx="6" ry="6" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part leg-wheels" style="display: none">
              <g id="wheel-l-roll" style="transform-origin: 65px 172px">
                <circle cx="65" cy="172" r="13" class="skin" style="fill: #ffe76a"/>
                <circle cx="65" cy="172" r="5" fill="rgba(0,0,0,0.12)"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-leg-quad-back-blob-left" class="layer" style="z-index: 1">
          <g class="part leg-quad-back-blob" style="display: none">
            <g id="knee-l-b-blob-wrap" style="transform-origin: 67.5px 160px">
              <rect x="60" y="155" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
              <g id="knee-l-b-blob" style="transform-origin: 67.5px 165px">
                <circle cx="67.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
                <path d="M 60 162 L 60 168 C 60 178, 75 178, 75 168 L 75 162 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-leg-quad-back-blob-right" class="layer" style="z-index: 1">
          <g class="part leg-quad-back-blob" style="display: none">
            <g id="knee-r-b-blob-wrap" style="transform-origin: 132.5px 160px">
              <rect x="125" y="155" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
              <g id="knee-r-b-blob" style="transform-origin: 132.5px 165px">
                <circle cx="132.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
                <path d="M 140 162 L 140 168 C 140 178, 125 178, 125 168 L 125 162 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-leg-quad-front-left" class="layer">
          <g class="part leg-quad-front" style="display: none">
            <g id="knee-l-f-wrap" style="transform-origin: 67.5px 160px">
              <rect x="60" y="155" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
              <g id="knee-l-f" style="transform-origin: 67.5px 165px">
                <circle cx="67.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
                <path d="M 60 162 L 60 168 C 60 178, 75 178, 75 168 L 75 162 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-leg-quad-front-right" class="layer">
          <g class="part leg-quad-front" style="display: none">
            <g id="knee-r-f-wrap" style="transform-origin: 132.5px 160px">
              <rect x="125" y="155" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
              <g id="knee-r-f" style="transform-origin: 132.5px 165px">
                <circle cx="132.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
                <path d="M 140 162 L 140 168 C 140 178, 125 178, 125 168 L 125 162 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-arm-left" class="layer" style="z-index: 5">
          <g id="anim-arm-left" style="transform-origin: 35px 125px">
            <g class="part arm-u" >
              <path d="M 35 125 C 20 125, 20 140, 35 140" class="arm-outline" style="display: none"/>
              <path d="M 35 125 C 20 125, 20 140, 35 140 C 45 140, 45 125, 35 125 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-circle" style="display: none">
              <path d="M 28 122 A 10 10 0 0 0 28 142" class="arm-outline" style="display: none"/>
              <path d="M 28 122 A 10 10 0 0 0 28 142 A 10 10 0 0 0 28 122 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-c" style="display: none">
              <path d="M 35 125 Q 25 132.5 35 140" class="arm-outline" style="display: none"/>
              <path d="M 35 125 Q 25 132.5 35 140 Q 42 132.5 35 125 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-block" style="display: none">
              <path d="M 31 120 L 39 120 A 6 6 0 0 1 45 126 L 45 139 A 6 6 0 0 1 39 145 L 31 145 A 6 6 0 0 1 25 139 L 25 126 A 6 6 0 0 1 31 120 Z" class="arm-outline" style="display: none"/>
              <path d="M 31 120 L 39 120 A 6 6 0 0 1 45 126 L 45 139 A 6 6 0 0 1 39 145 L 31 145 A 6 6 0 0 1 25 139 L 25 126 A 6 6 0 0 1 31 120 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-vertical" style="display: none">
              <path d="M 28 126 L 28 132 C 28 142, 42 142, 42 132 L 42 126" class="arm-outline" style="display: none"/>
              <rect x="28" y="120" width="14" height="9" rx="7" class="skin" style="fill: #ffe76a"/>
              <g style="transform-origin: 35px 129px">
                <circle cx="35" cy="129" r="7" class="skin" style="fill: #ffe76a"/>
                <path d="M 28 126 L 28 132 C 28 142, 42 142, 42 132 L 42 126 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-leg-right" class="layer" style="z-index: 5">
          <g id="anim-leg-right" style="transform-origin: 135px 160px">
            <g class="part leg-biped" >
              <rect x="125" y="155" width="15" height="17.5" rx="7.5" class="skin" style="fill: #ffe76a"/>
              <g id="anim-knee-right" style="transform-origin: 132.5px 165px">
                <circle cx="132.5" cy="165" r="7.5" class="skin" style="fill: #ffe76a"/>
                <path d="M 140 162 L 140 168 C 140 178, 125 178, 125 168 L 125 162 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
            <g class="part leg-octo" style="display: none">
              <g transform="translate(115, 162) rotate(0)">
                <g id="ten-r-0-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-r-0-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M 7.5 2 L 7.5 8 C 7.5 18, -7.5 18, -7.5 8 L -7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
              <g transform="translate(135, 162) rotate(20)">
                <g id="ten-r-1-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-r-1-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M 7.5 2 L 7.5 8 C 7.5 18, -7.5 18, -7.5 8 L -7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
              <g transform="translate(152, 158) rotate(42)">
                <g id="ten-r-3-wrap" style="transform-origin: 0px 0px">
                  <rect x="-7.5" y="-5" width="15" height="10" rx="7.5" class="skin" style="fill: #ffe76a"/>
                  <g id="ten-r-3-knee" style="transform-origin: 0px 5px">
                    <circle cx="0" cy="5" r="7.5" class="skin" style="fill: #ffe76a"/>
                    <path d="M 7.5 2 L 7.5 8 C 7.5 18, -7.5 18, -7.5 8 L -7.5 2 Z" class="skin" style="fill: #ffe76a"/>
                  </g>
                </g>
              </g>
            </g>
            <g class="part leg-block" style="display: none">
              <rect x="125" y="150" width="20" height="35" rx="6" ry="6" class="arm-outline" style="display: none"/>
              <rect x="125" y="150" width="20" height="35" rx="6" ry="6" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part leg-wheels" style="display: none">
              <g id="wheel-r-roll" style="transform-origin: 135px 172px">
                <circle cx="135" cy="172" r="13" class="skin" style="fill: #ffe76a"/>
                <circle cx="135" cy="172" r="5" fill="rgba(0,0,0,0.12)"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-arm-right" class="layer" style="z-index: 5">
          <g id="anim-arm-right" style="transform-origin: 165px 125px">
            <g class="part arm-u" >
              <path d="M 165 125 C 180 125, 180 140, 165 140" class="arm-outline" style="display: none"/>
              <path d="M 165 125 C 180 125, 180 140, 165 140 C 155 140, 155 125, 165 125 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-circle" style="display: none">
              <path d="M 172 122 A 10 10 0 0 1 172 142" class="arm-outline" style="display: none"/>
              <path d="M 172 122 A 10 10 0 0 1 172 142 A 10 10 0 0 1 172 122 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-c" style="display: none">
              <path d="M 165 125 Q 175 132.5 165 140" class="arm-outline" style="display: none"/>
              <path d="M 165 125 Q 175 132.5 165 140 Q 158 132.5 165 125 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-block" style="display: none">
              <path d="M 161 120 L 169 120 A 6 6 0 0 1 175 126 L 175 139 A 6 6 0 0 1 169 145 L 161 145 A 6 6 0 0 1 155 139 L 155 126 A 6 6 0 0 1 161 120 Z" class="arm-outline" style="display: none"/>
              <path d="M 161 120 L 169 120 A 6 6 0 0 1 175 126 L 175 139 A 6 6 0 0 1 169 145 L 161 145 A 6 6 0 0 1 155 139 L 155 126 A 6 6 0 0 1 161 120 Z" class="skin skin-fill" style="fill: #ffe76a; stroke: none"/>
            </g>
            <g class="part arm-vertical" style="display: none">
              <path d="M 158 126 L 158 132 C 158 142, 172 142, 172 132 L 172 126" class="arm-outline" style="display: none"/>
              <rect x="158" y="120" width="14" height="9" rx="7" class="skin" style="fill: #ffe76a"/>
              <g style="transform-origin: 165px 129px">
                <circle cx="165" cy="129" r="7" class="skin" style="fill: #ffe76a"/>
                <path d="M 172 126 L 172 132 C 172 142, 158 142, 158 132 L 158 126 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-body" class="layer" style="z-index: 2">
          <g class="part body-round" >
            <rect x="33" y="80" width="134" height="85" rx="42.5" class="skin" style="fill: #ffe76a"/>
            <ellipse cx="100" cy="128" rx="44" ry="30" class="belly body-belly" style="fill: rgba(255, 255, 255, 0.58); display: none"/>
            <path d="M 58 96 C 67 86, 83 83, 95 85" class="toon-highlight" opacity="0.75" style="display: none"/>
          </g>
          <g class="part body-square" style="display: none">
            <rect x="35" y="80" width="130" height="85" rx="20" class="skin" style="fill: #ffe76a"/>
            <rect x="62" y="103" width="76" height="46" rx="24" class="belly body-belly" style="fill: rgba(255, 255, 255, 0.58); display: none"/>
            <path d="M 55 94 C 69 86, 88 85, 103 88" class="toon-highlight" opacity="0.72" style="display: none"/>
          </g>
          <g class="part body-chicken" >
            <path d="M 78 86 Q 100 101 122 86" class="toon-line" opacity="0.18" style="fill: none; stroke: #1a1a1a; stroke-width: 3.4px; stroke-linecap: round; stroke-linejoin: round"/>
          </g>
          <g class="part body-frog" style="display: none">
            <circle cx="62" cy="119" r="4" fill="rgba(26, 26, 26, 0.18)"/>
            <circle cx="138" cy="119" r="4" fill="rgba(26, 26, 26, 0.18)"/>
          </g>
          <g class="part body-bear body-bunny body-axolotl body-tanuki" style="display: none">
            <path d="M 77 139 Q 100 151 123 139" class="toon-line" opacity="0.18" style="fill: none; stroke: #1a1a1a; stroke-width: 3.4px; stroke-linecap: round; stroke-linejoin: round"/>
          </g>
          <g class="part body-robot" style="display: none">
            <rect x="72" y="108" width="56" height="34" rx="10" fill="rgba(255,255,255,0.18)" stroke="#1a1a1a" stroke-width="3"/>
            <circle cx="87" cy="125" r="3.5" fill="#67e8f9"/>
            <circle cx="100" cy="125" r="3.5" fill="#fef08a"/>
            <circle cx="113" cy="125" r="3.5" fill="#fb7185"/>
          </g>
        </g>
        <g id="layer-belly" class="layer" style="z-index: 19">
          <g id="belly-clip">
            <g id="anim-belly-patch" style="transform-origin: 100px 147px">
              <g class="part belly-patch" style="display: none">
                <rect x="70" y="132" width="60" height="30" rx="15" ry="15" class="belly" style="fill: rgba(255, 255, 255, 0.58)"/>
              </g>
            </g>
          </g>
        </g>
        <g id="layer-head" class="layer" style="z-index: 4; transform-origin: 50% 65%">
          <g id="group-ears">
            <g id="anim-ear-left" style="transform-origin: 65px 80px">
              <g class="part ears-bunny" transform="translate(0 -18)" style="display: none">
                <path d="M 65 38 C 45 -22, 80 -22, 90 38 L 90 80 L 65 80 Z" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-bunny-inner" transform="translate(0 -18)" style="display: none">
                <path d="M 66 41 C 56 3, 76 3, 82 40 L 82 74 L 66 74 Z" fill="#1a1a1a" opacity="0.15"/>
              </g>
              <g class="part ears-bear" transform="translate(-10 -3)" style="display: none">
                <circle cx="64" cy="34" r="19" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-bear-inner" transform="translate(-10 -3)" style="display: none">
                <circle cx="64" cy="34" r="8" fill="#1a1a1a" opacity="0.15"/>
              </g>
              <g class="part ears-goat" transform="translate(-14 -2)" style="display: none">
                <path d="M 92 46 Q 72 6 38 12 Q 56 34 74 48" fill="#f1f5f9"/>
                <path d="M 68 60 Q 34 59 34 77 Q 48 78 68 71" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-axolotl" transform="translate(-10 0)" style="display: none">
                <path d="M 65 45 Q 35 25 25 40 Q 50 55 65 60" class="skin" style="fill: #ffe76a"/>
                <path d="M 65 60 Q 30 55 25 70 Q 50 75 65 75" class="skin" style="fill: #ffe76a"/>
                <path d="M 65 75 Q 40 90 45 105 Q 60 90 70 85" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-tanuki" transform="translate(-10 -1)" style="display: none">
                <path d="M 80 44 C 44 14, 20 36, 46 70 L 80 86 Z" class="skin" style="fill: #ffe76a"/>
                <path d="M 66 50 C 50 35, 38 45, 54 61 Z" fill="#1a1a1a" opacity="0.15"/>
              </g>
              <g class="part ears-robot" transform="translate(-10 0)" style="display: none">
                <path d="M 65 55 L 40 55 C 35 55, 35 60, 35 65 L 25 65 C 20 65, 20 80, 25 80 L 35 80 L 35 85 C 35 90, 40 90, 45 90 L 65 90 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
            <g id="anim-ear-right" style="transform-origin: 135px 80px">
              <g class="part ears-bunny" transform="translate(0 -18)" style="display: none">
                <path d="M 135 38 C 155 -22, 120 -22, 110 38 L 110 80 L 135 80 Z" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-bunny-inner" transform="translate(0 -18)" style="display: none">
                <path d="M 134 41 C 144 3, 124 3, 118 40 L 118 74 L 134 74 Z" fill="#1a1a1a" opacity="0.15"/>
              </g>
              <g class="part ears-bear" transform="translate(10 -3)" style="display: none">
                <circle cx="136" cy="34" r="19" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-bear-inner" transform="translate(10 -3)" style="display: none">
                <circle cx="136" cy="34" r="8" fill="#1a1a1a" opacity="0.15"/>
              </g>
              <g class="part ears-goat" transform="translate(14 -2)" style="display: none">
                <path d="M 108 46 Q 128 6 162 12 Q 144 34 126 48" fill="#f1f5f9"/>
                <path d="M 132 60 Q 166 59 166 77 Q 152 78 132 71" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-axolotl" transform="translate(10 0)" style="display: none">
                <path d="M 135 45 Q 165 25 175 40 Q 150 55 135 60" class="skin" style="fill: #ffe76a"/>
                <path d="M 135 60 Q 170 55 175 70 Q 150 75 135 75" class="skin" style="fill: #ffe76a"/>
                <path d="M 135 75 Q 160 90 155 105 Q 140 90 130 85" class="skin" style="fill: #ffe76a"/>
              </g>
              <g class="part ears-tanuki" transform="translate(10 -1)" style="display: none">
                <path d="M 120 44 C 156 14, 180 36, 154 70 L 120 86 Z" class="skin" style="fill: #ffe76a"/>
                <path d="M 134 50 C 150 35, 162 45, 146 61 Z" fill="#1a1a1a" opacity="0.15"/>
              </g>
              <g class="part ears-robot" transform="translate(10 0)" style="display: none">
                <path d="M 135 55 L 160 55 C 165 55, 165 60, 165 65 L 175 65 C 180 65, 180 80, 175 80 L 165 80 L 165 85 C 165 90, 160 90, 155 90 L 135 90 Z" class="skin" style="fill: #ffe76a"/>
              </g>
            </g>
            <g id="anim-ear-center" style="transform-origin: 100px 85px">
              <g class="part ears-chicken" >
                <path d="M 80 25 C 75 -5, 90 -5, 100 10 C 110 -5, 125 -5, 120 25 Z" fill="#ff4d4d"/>
              </g>
            </g>
          </g>
          <g id="group-bulges">
            <g id="anim-bulge-left" class="face-layout-frog" style="display: none; transform-origin: 70px 60px">
              <circle cx="70" cy="45" r="26" class="part ears-frog skin" style="fill: #ffe76a; display: none"/>
            </g>
            <g id="anim-bulge-right" class="face-layout-frog" style="display: none; transform-origin: 130px 60px">
              <circle cx="130" cy="45" r="26" class="part ears-frog skin" style="fill: #ffe76a; display: none"/>
            </g>
            <g id="anim-octo-bulge-left" class="face-layout-octo" style="display: none; transform-origin: 70px 60px">
              <circle cx="70" cy="45" r="26" class="part ears-octo skin" style="fill: #ffe76a; display: none"/>
            </g>
            <g id="anim-octo-bulge-right" class="face-layout-octo" style="display: none; transform-origin: 130px 60px">
              <circle cx="130" cy="45" r="26" class="part ears-octo skin" style="fill: #ffe76a; display: none"/>
            </g>
          </g>
          <circle cx="100" cy="85" r="75" class="skin" style="fill: #ffe76a"/>
          <path d="M 58 44 C 74 29, 103 24, 125 31 C 98 34, 76 43, 62 59 Z" class="toon-highlight" opacity="0.7" style="display: none"/>
          <path d="M 149 70 C 156 91, 149 120, 128 142 C 151 135, 169 112, 171 87 C 168 78, 160 72, 149 70 Z" class="toon-shadow" style="display: none; fill: rgba(30, 30, 30, 0.1)"/>
        </g>
      </g>
    </g>
    <g id="front-group" style="z-index: 22">
    </g>
    <g id="layer-hover-thruster" class="layer layer-hover-thruster">
      <g class="part leg-hover" style="display: none">
        <g id="hover-thruster-pulse" style="transform-origin: 100px 168px">
          <path d="M 100 158 L 118 188 L 82 188 Z" fill="url(#hover-beam-grad)"/>
          <ellipse cx="100" cy="175" rx="14" ry="4" fill="#67e8f9" fill-opacity="0.35"/>
          <ellipse cx="100" cy="182" rx="20" ry="5" fill="#22d3ee" fill-opacity="0.25"/>
          <ellipse cx="100" cy="188" rx="26" ry="6" fill="#06b6d4" fill-opacity="0.2"/>
          <rect x="94" y="158" width="3" height="22" rx="1" fill="#7dd3fc" fill-opacity="0.5"/>
          <rect x="100" y="158" width="3" height="26" rx="1" fill="#38bdf8" fill-opacity="0.45"/>
          <rect x="106" y="158" width="3" height="20" rx="1" fill="#7dd3fc" fill-opacity="0.5"/>
        </g>
      </g>
    </g>
    <g id="layer-face" class="layer" style="z-index: 20; transform-origin: 50% 65%">
      <g clip-path="url(#head-clip-mask)">
        <g id="group-face-clipped">
          <g class="part face-tanuki" style="display: none">
            <path d="M 45 75 C 30 65, 70 60, 80 80 C 75 100, 35 95, 45 75 Z" fill="#1a1a1a" opacity="0.2"/>
            <path d="M 155 75 C 170 65, 130 60, 120 80 C 125 100, 165 95, 155 75 Z" fill="#1a1a1a" opacity="0.2"/>
          </g>
          <g class="part face-axolotl" style="display: none">
            <circle cx="72" cy="61" r="3" fill="rgba(26, 26, 26, 0.18)"/>
            <circle cx="128" cy="61" r="3" fill="rgba(26, 26, 26, 0.18)"/>
          </g>
          <g class="part face-robot" style="display: none">
            <path d="M 45 45 Q 100 60 155 45" fill="none" stroke="#1a1a1a" stroke-width="4" stroke-linecap="round" stroke-dasharray="12 8"/>
            <path d="M 40 115 Q 100 140 160 115" fill="none" stroke="#1a1a1a" stroke-width="4" stroke-linecap="round"/>
            <line x1="60" y1="123" x2="60" y2="133" stroke="#1a1a1a" stroke-width="4" stroke-linecap="round"/>
            <line x1="140" y1="123" x2="140" y2="133" stroke="#1a1a1a" stroke-width="4" stroke-linecap="round"/>
            <line x1="100" y1="128" x2="100" y2="138" stroke="#1a1a1a" stroke-width="4" stroke-linecap="round"/>
            <g transform="translate(45, 95) rotate(-15)">
              <circle cx="0" cy="0" r="7" fill="#e2e8f0" stroke="#1a1a1a" stroke-width="3"/>
              <line x1="-5" y1="-5" x2="5" y2="5" stroke="#1a1a1a" stroke-width="3" stroke-linecap="round"/>
            </g>
            <g transform="translate(155, 95) rotate(15)">
              <circle cx="0" cy="0" r="7" fill="#e2e8f0" stroke="#1a1a1a" stroke-width="3"/>
              <line x1="-5" y1="5" x2="5" y2="-5" stroke="#1a1a1a" stroke-width="3" stroke-linecap="round"/>
            </g>
          </g>
          <g class="face-layout-standard" style="display: block">
            <ellipse class="standard-blush" cx="45" cy="93" rx="15" ry="8" fill="#ff8fa3" opacity="0.76" transform="rotate(-15 45 93)" style="display: block"/>
            <ellipse class="standard-blush" cx="155" cy="93" rx="15" ry="8" fill="#ff8fa3" opacity="0.76" transform="rotate(15 155 93)" style="display: block"/>
            <g class="part eye-base" style="display: block">
              <ellipse cx="60" cy="80" rx="11" ry="13" fill="#1a1a1a"/>
              <ellipse cx="140" cy="80" rx="11" ry="13" fill="#1a1a1a"/>
            </g>
            <g class="part eye-pupil" >
              <circle cx="57" cy="74" r="4" fill="#ffffff"/>
              <circle cx="137" cy="74" r="4" fill="#ffffff"/>
              <circle cx="63" cy="84" r="1.8" fill="#ffffff" opacity="0.85"/>
              <circle cx="143" cy="84" r="1.8" fill="#ffffff" opacity="0.85"/>
            </g>
            <g class="part eye-sleep" style="display: none">
              <path d="M 53 82 Q 60 88 67 82" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round"/>
              <path d="M 133 82 Q 140 88 147 82" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round"/>
            </g>
            <g class="part face-bear" style="display: none">
              <ellipse cx="100" cy="90" rx="17" ry="12" fill="rgba(255,245,235,0.75)"/>
              <ellipse cx="100" cy="86" rx="5.5" ry="4.5" fill="#1a1a1a"/>
              <path class="bear-mouth-connector" d="M 100 90 C 100 91.4, 100 92.6, 100 93.8" fill="none" stroke="#1a1a1a" stroke-width="3" stroke-linecap="round"/>
            </g>
          </g>
          <g class="face-layout-frog" style="display: none">
            <g id="anim-frogcheek-left" style="transform-origin: 70px 60px">
              <ellipse cx="50" cy="65" rx="14" ry="7" fill="#ff8fa3" opacity="0.8" transform="rotate(-20 50 65)"/>
            </g>
            <g id="anim-frogcheek-right" style="transform-origin: 130px 60px">
              <ellipse cx="150" cy="65" rx="14" ry="7" fill="#ff8fa3" opacity="0.8" transform="rotate(20 150 65)"/>
            </g>
          </g>
          <g id="anim-mouth">
            <g class="part face-chicken" >
              <g id="anim-chicken-wattle" style="transform-origin: 100px 107px">
                <path d="M 91.55 107
                           Q 100 100.5 108.45 107
                           C 112.68 109.5, 115.5 112.8, 114.09 116
                           C 112.68 118.5, 108.45 119.2, 103.38 118.4
                           C 101.41 118.1, 100.42 117.45, 100 117.2
                           C 99.58 117.45, 98.59 118.1, 97.25 118.4
                           C 91.55 119.2, 87.32 118.5, 85.91 116
                           C 84.5 112.8, 87.32 109.5, 91.55 107
                           Z" fill="#ff4d4d" stroke="#1a1a1a" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>
              </g>
              <circle cx="100" cy="96" r="11" fill="#ff9900" stroke="#1a1a1a" stroke-width="3"/>
            </g>
            <g class="mouth-chicken-clip">
              <g class="part mouth-happy" style="display: none">
                <path d="M 89 92 Q 100 105 111 92" fill="none" stroke="#1a1a1a" stroke-width="4.8" stroke-linecap="round"/>
              </g>
              <g class="part mouth-sad" style="display: none">
                <path d="M 90 100 Q 100 90 110 100" fill="none" stroke="#1a1a1a" stroke-width="5" stroke-linecap="round"/>
              </g>
              <g class="part mouth-cat" >
                <path d="M 91 92 C 91 101, 100 101, 100 94 C 100 101, 109 101, 109 92" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g class="part mouth-scared" style="display: none">
                <path d="M 80 96 L 85 92 L 90 98 L 95 92 L 100 98 L 105 92 L 110 98 L 115 92 L 120 96" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round" stroke-linejoin="round"/>
              </g>
              <g class="part mouth-open" style="display: none">
                <path d="M 89 94 Q 100 98 111 94 A 11 12 0 0 1 89 94 Z" fill="#1a1a1a" stroke="#1a1a1a" stroke-width="3" stroke-linejoin="round"/>
                <path d="M 95 102 Q 100 99 105 102 A 5 4 0 0 1 95 102 Z" fill="#ff8fa3"/>
              </g>
              <g class="part mouth-panting" style="display: none">
                <g id="pant-closed">
                  <path d="M 94 95 Q 100 93 106 95" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round"/>
                </g>
                <g id="pant-inhale" style="display: none">
                  <ellipse cx="100" cy="96" rx="4.5" ry="6" fill="#1a1a1a"/>
                </g>
              </g>
              <g class="part mouth-tiny-smile" style="display: none">
                <path d="M 94 95 Q 100 99 106 95" fill="none" stroke="#1a1a1a" stroke-width="4.2" stroke-linecap="round"/>
              </g>
              <g class="part mouth-surprised" style="display: none">
                <ellipse cx="100" cy="96" rx="5.5" ry="7" fill="#1a1a1a"/>
                <ellipse cx="100" cy="94" rx="2" ry="2.8" fill="rgba(255,255,255,0.35)"/>
              </g>
              <g class="part mouth-determined" style="display: none">
                <path d="M 88 96 Q 100 92 112 96" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round"/>
                <path d="M 92 92 L 96 96 M 104 96 L 108 92" fill="none" stroke="#1a1a1a" stroke-width="2.8" stroke-linecap="round" opacity="0.75"/>
              </g>
            </g>
          </g>
          <g class="part face-octo" style="display: none">
            <circle id="anim-octo-mouth-inner" cx="100" cy="80" r="4" fill="#6b6bff" opacity="0.8"/>
            <path id="anim-octo-mouth-arc-left" d="M 106 70 A 12 12 0 1 0 106 90" fill="none" stroke="#1a1a1a" stroke-width="3" stroke-linecap="round"/>
            <path id="anim-octo-mouth-arc-right" d="M 94 70 A 12 12 0 1 1 94 90" fill="none" stroke="#1a1a1a" stroke-width="3" stroke-linecap="round"/>
          </g>
        </g>
      </g>
      <g id="group-face-unclipped">
        <g class="part face-octo" style="display: none">
          <circle cx="85" cy="35" r="2" fill="#6b6bff" opacity="0.7"/>
          <circle cx="95" cy="30" r="1.5" fill="#6b6bff" opacity="0.7"/>
          <circle cx="105" cy="33" r="2" fill="#6b6bff" opacity="0.7"/>
          <circle cx="115" cy="37" r="1.5" fill="#6b6bff" opacity="0.7"/>
          <circle cx="90" cy="45" r="1.5" fill="#6b6bff" opacity="0.7"/>
          <circle cx="100" cy="40" r="2" fill="#6b6bff" opacity="0.7"/>
          <circle cx="110" cy="43" r="1.5" fill="#6b6bff" opacity="0.7"/>
          <circle cx="120" cy="50" r="2" fill="#6b6bff" opacity="0.7"/>
          <circle cx="80" cy="50" r="1.5" fill="#6b6bff" opacity="0.7"/>
          <circle cx="125" cy="55" r="1.5" fill="#6b6bff" opacity="0.7"/>
          <circle cx="75" cy="58" r="2" fill="#6b6bff" opacity="0.7"/>
          <circle cx="130" cy="62" r="2" fill="#6b6bff" opacity="0.7"/>
          <circle cx="70" cy="68" r="1.5" fill="#6b6bff" opacity="0.7"/>
        </g>
        <g class="face-layout-frog" style="display: none">
          <g id="anim-frogeye-left" style="transform-origin: 70px 60px">
            <ellipse class="part eye-base" cx="70" cy="50" rx="12" ry="15" fill="#1a1a1a" transform="rotate(-15 70 50)" style="display: block"/>
            <circle class="part eye-pupil" cx="67" cy="43" r="4" fill="#ffffff" />
            <circle class="part eye-pupil" cx="72" cy="54" r="1.8" fill="#ffffff" opacity="0.85" />
            <path class="part eye-sleep" d="M 60 48 Q 67 55 74 48" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round" transform="rotate(-15 67 51)" style="display: none"/>
          </g>
          <g id="anim-frogeye-right" style="transform-origin: 130px 60px">
            <ellipse class="part eye-base" cx="130" cy="50" rx="12" ry="15" fill="#1a1a1a" transform="rotate(15 130 50)" style="display: block"/>
            <circle class="part eye-pupil" cx="127" cy="43" r="4" fill="#ffffff" />
            <circle class="part eye-pupil" cx="132" cy="54" r="1.8" fill="#ffffff" opacity="0.85" />
            <path class="part eye-sleep" d="M 126 48 Q 133 55 140 48" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round" transform="rotate(15 133 51)" style="display: none"/>
          </g>
        </g>
        <g class="face-layout-octo" style="display: none">
          <g id="anim-octoeye-left" style="transform-origin: 70px 60px">
            <ellipse class="part eye-base" cx="70" cy="50" rx="12" ry="15" fill="#1a1a1a" transform="rotate(-15 70 50)" style="display: block"/>
            <circle class="part eye-pupil" cx="67" cy="43" r="4" fill="#ffffff" />
            <circle class="part eye-pupil" cx="72" cy="54" r="1.8" fill="#ffffff" opacity="0.85" />
            <path class="part eye-sleep" d="M 60 48 Q 67 55 74 48" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round" transform="rotate(-15 67 51)" style="display: none"/>
          </g>
          <g id="anim-octoeye-right" style="transform-origin: 130px 60px">
            <ellipse class="part eye-base" cx="130" cy="50" rx="12" ry="15" fill="#1a1a1a" transform="rotate(15 130 50)" style="display: block"/>
            <circle class="part eye-pupil" cx="127" cy="43" r="4" fill="#ffffff" />
            <circle class="part eye-pupil" cx="132" cy="54" r="1.8" fill="#ffffff" opacity="0.85" />
            <path class="part eye-sleep" d="M 126 48 Q 133 55 140 48" fill="none" stroke="#1a1a1a" stroke-width="4.5" stroke-linecap="round" transform="rotate(15 133 51)" style="display: none"/>
          </g>
        </g>
      </g>
      <g id="group-face-top-unclipped">
        <g class="part face-tanuki" style="display: none">
          <g transform="translate(100, 18) rotate(20) scale(1.45)">
            <path d="M 0 -13 C -13 0, 0 13, 0 13 C 0 13, 13 0, 0 -13 Z" fill="#8BD044" stroke="#1a1a1a" stroke-width="2.5" stroke-linejoin="round"/>
            <line x1="0" y1="-9" x2="0" y2="9" stroke="#1a1a1a" stroke-width="1.8" stroke-linecap="round"/>
          </g>
        </g>
      </g>
      <g id="group-face-top-pole">
        <g class="part ears-robot" style="display: none">
          <g id="anim-robot-antenna" style="transform-origin: 100px 12px">
            <rect x="96" y="-31" width="8" height="30" class="skin" stroke="#1a1a1a" stroke-width="4.5" style="fill: #ffe76a"/>
            <line x1="93" y1="-11" x2="107" y2="-11" stroke="#1a1a1a" stroke-width="4" stroke-linecap="round"/>
            <line x1="93" y1="-21" x2="107" y2="-21" stroke="#1a1a1a" stroke-width="4" stroke-linecap="round"/>
            <path d="M 86 12 L 114 12 L 105 2 L 95 2 Z" class="skin" stroke="#1a1a1a" stroke-width="4.5" stroke-linejoin="round" style="fill: #ffe76a"/>
            <circle cx="100" cy="-36" r="14" class="skin" stroke="#1a1a1a" stroke-width="4.5" style="fill: #ffe76a"/>
            <circle cx="100" cy="-36" r="6" fill="#00ffcc"/>
            <circle cx="100" cy="-38" r="2" fill="#ffffff" opacity="0.8"/>
          </g>
        </g>
      </g>
    </g>
  </g>
</svg>
)RIGSVG";

#endif // RAYSVG_SMOKE_ASSET_H
